= Inline HTML
Author Name
:idprefix:
:idseparator: -
:!example-caption:
:!table-caption:

Below is some inline html which can be be used in documentation to display rich content not possible with just asciidocs.

- The classes used on the html element below are all defined in `doc-home.css`
- If you change the styles in `doc-home.css`, you'll need to generate a new `ui-bundle.zip` before the changes will show up on the actual documentation site.
- The html below and be copy / pasted into any doc, and will inherit the styles
- Be careful not to change any classes after copy / pasting the snippets below into the documentation, otherwise the styles will break


## Card Grid
A grid of cards which can link to a specific documentation page.

- You can edit anything within the `a` tag without breaking any styles.
- You can add as many `a` tags within the `home-card-grid` as you wish, css will automatically position all children in the grid.
- It is best to keep images around `100x100` in size, and in svg format.

++++

<div class="html-container"> 
    <div class="home-cards-grid">

        <a class="home-card" href="#">  
            <img src="./cube.svg" alt="cube icon" />
            <h3 class="home-card-header">Get the SDK</h3>
            <p>Download the full SDK to write code that runs directly on the internet.</p>
        </a>

        <a class="home-card" href="#">
            <img src="./rocket.svg" alt="rocket icon" />
            <h3 class="home-card-header">Quick Start</h3>
            <p>Deploy your first code to the Internet Computer in minutes.</p>
        </a>

        <a class="home-card" href="#">
            <img src="./lightbulb.svg" alt="lightbulb icon" />
            <h3 class="home-card-header">Get Samples</h3>
            <p>Access sample code, applications, and microservices.</p>
        </a>

        <a class="home-card" href="#">
            <img src="./code-editor.svg" alt="code editor icon" />
            <h3 class="home-card-header">Developer’s<br/>Guide</h3>
            <p>Take a deeper dive into how you can use the SDK to create applications.</p>
        </a>

        <a class="home-card" href="#">
            <img src="./stack.svg" alt="stack icon" />
            <h3 class="home-card-header">Language</br>Guide</h3>
            <p>Explore Motoko, the  programming language for the Internet Computer.</p>
        </a>

        <a class="home-card" href="#">
            <img src="./conversation.svg" alt="conversation icon" />
            <h3 class="home-card-header">Developer<br>Forum</h3>
            <p>Learn, connect, and engage with the growing DFINITY developer community.</p>
        </a>
    </div>
</div>

++++


## Featured Articles
Two columns of cards that can be used to highlight documents of interest.

- You can edit anything within the `a` tag without breaking any styles.
- You can add as many `a` tags within the `featured-article-column` as you wish, css will automatically position all children in the grid.

++++

<div class="html-wrapper">
    <div class="featured-articles-grid">

        <div class="featured-article-column">
            <h3 class="featured-article-header">Featured Articles</h3>

            <a class="featured-article-card">
                <span class="featured-article-title-wrapper">
                    <img src="./document.svg" alt="document icon" />
                    <p>Passing Arguments</p>
                </span>
                <svg width="7" height="13" viewBox="0 0 7 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1 1L6 6.5L1 12" stroke="black"/>
                </svg>
            </a>

            <a class="featured-article-card">
                <span class="featured-article-title-wrapper">
                    <img src="./document.svg" alt="document icon" />
                    <p>Passing Arguments</p>
                </span>
                <svg width="7" height="13" viewBox="0 0 7 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1 1L6 6.5L1 12" stroke="black"/>
                </svg>
            </a>

            <a class="featured-article-card">
                <span class="featured-article-title-wrapper">
                    <img src="./document.svg" alt="document icon" />
                    <p>Passing Arguments</p>
                </span>
                <svg width="7" height="13" viewBox="0 0 7 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1 1L6 6.5L1 12" stroke="black"/>
                </svg>
            </a>
        </div>

        <div class="featured-article-column">
            <h3 class="featured-article-header">Popular Topics</h3>

            <a class="featured-article-card">
                <span class="featured-article-title-wrapper">
                    <img src="./document.svg" alt="document icon" />
                    <p>Passing Arguments</p>
                </span>
                <svg width="7" height="13" viewBox="0 0 7 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1 1L6 6.5L1 12" stroke="black"/>
                </svg>
            </a>

            <a class="featured-article-card">
                <span class="featured-article-title-wrapper">
                    <img src="./document.svg" alt="document icon" />
                    <p>Passing Arguments</p>
                </span>
                <svg width="7" height="13" viewBox="0 0 7 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1 1L6 6.5L1 12" stroke="black"/>
                </svg>
            </a>

            <a class="featured-article-card">
                <span class="featured-article-title-wrapper">
                    <img src="./document.svg" alt="document icon" />
                    <p>Passing Arguments</p>
                </span>
                <svg width="7" height="13" viewBox="0 0 7 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1 1L6 6.5L1 12" stroke="black"/>
                </svg>

            </a>
        </div>        
    </div>

</div>

++++

## Advanced: Inline <style>

If one of the above snippets don't work for you, you can always create new ones, add the styles to `doc-home.css`, and publish a new bundle.
However, in certain scenarios, this might feel like an unnecessary amount of work. Another option, is to use a style tag within the asciidoc itself, see below for an example:

[NOTE]
====
If use a `<style>` tag, remeber to the following:

-  Add vendor prefixes if necessary as the CSS won't be run through `postcss`
- use the `.doc` selector before any custom classes to properly target the element
====

++++

<style>
.doc .pink_text {
    color: pink;
}
</style>

<h1 class="pink_text">Hey, check out this pink text</h1>

++++
