= Hardware and Software Requirements
Author Name
:idprefix:
:idseparator: -
:!example-caption:
:!table-caption:
:page-repl: repl

image:multirepo-ssg.svg[Multirepo SSG,200,float=right]
Platonem complectitur mediocritatem ea eos.
Ei nonumy deseruisse ius.
Mel id omnes verear.
Vis no velit audiam, sonet <<dependencies,praesent>> eum ne.
*Prompta eripuit* nec ad.
Integer diam enim, dignissim eget eros et, ultricies mattis odio.
Vestibulum consectetur nec urna a luctus.
Quisque pharetra tristique arcu fringilla dapibus.
Curabitur ut massa aliquam, cursus enim et, accumsan lectus.


= Header 1

== Header 2

== Header 2
== Header 2
== Header 2
== Header 2

== Header 2
== Header 2
== Header 2

== Header 2 that is really long and wraps
== Header 2
== Header 2
== Header 2
== Header 2
== Header 2
== Header 2
== Header 2


=== Header 3 (don't show up in sidebar)

==== Header 4 (doesn't show up in sidebar)

Paragraph.

[source, motoko]
----
actor Counter {
  var value = 0;
  public func inc() : async Nat {
    value += 1;
    return value;
  };
}
----

Show results as well.

[source, motoko-run]
----
let x = 3;
let y = x * x;
----

Run with base library.

[source, motoko-run]
....
import Debug "mo:base/Debug";
Debug.print "hello";
....

Show warnings.

[source, motoko-run]
----
{ x = 10 } == { y = 20 }
----

Non-Motoko source

[source, swift]
----
a single long line of text to make sure the copy button is correctly aligned within the code block
----

