= Hardware and Software Requirements
Author Name
:idprefix:
:idseparator: -
:!example-caption:
:!table-caption:
:page-repl: true
:page-moc-base-tag: dfx-0.6.12

image:multirepo-ssg.svg[Multirepo SSG,200,float=right]
Platonem complectitur mediocritatem ea eos.
Ei nonumy deseruisse ius.
Mel id omnes verear.
Vis no velit audiam, sonet <<dependencies,praesent>> eum ne.
*Prompta eripuit* nec ad.
Integer diam enim, dignissim eget eros et, ultricies mattis odio.
Vestibulum consectetur nec urna a luctus.
Quisque pharetra tristique arcu fringilla dapibus.
Curabitur ut massa aliquam, cursus enim et, accumsan lectus.


= Header 1

== Header 2

== Header 2
== Header 2
== Header 2
== Header 2

== Header 2
== Header 2
== Header 2

== Header 2 that is really long and wraps
== Header 2
== Header 2
== Header 2
== Header 2
== Header 2
== Header 2
== Header 2


=== Header 3 (don't show up in sidebar)

==== Header 4 (doesn't show up in sidebar)

Paragraph.

[source#counter, motoko]
----
actor Counter {
  var value = 0;  // <1>
  public func inc() : async Nat {
    value += 1;   // <2>
    return value;
  };
}
----
<1> counter value
<2> increment counter

Show results as well.

[source#x, motoko]
----
let x = 3;
----

[source#y.include_x, motoko]
----
let y = x * x;
----

[source.run.include_x_y, motoko]
----
let z = y * y;
----

Run with base library.

[source.run.include_counter, motoko]
....
// comments
import Debug "mo:base/Debug";
Debug.print /* hello */ "hello";
await Counter.inc();
....

Show warnings.

[source.run, motoko]
----
{ x = 10 } == { y = 20 }
----

Without repl
[source.no-repl, motoko]
----
actor {
  ...
}
----

Candid

[source, candid]
----
import "test.did";
type my_type = principal;
type List = opt record { head: int; tail: List };
type f = func (List, func (int32) -> (int64)) -> (opt List);
type broker = service {
  find : (name: text) ->
    (service {up:() -> (); current:() -> (nat32)});
};
type nested = record { nat; nat; record {nat;int;}; record { nat; 0x2a:nat; nat8; }; 42:nat; 40:nat; variant{ A; 0x2a; B; C }; };

service server : {
  f : (test: blob, opt bool) -> () oneway;
  g : (my_type, List, opt List, nested) -> (int, broker) query;
  h : (vec opt text, variant { A: nat; B: opt text }, opt List) -> (record { id: nat; 0x2a: record {} });
  i : f;
  "👀": (nat) -> (nat) query;
}
----

Non-Motoko source

[source, swift]
----
a single long line of text to make sure the copy button is correctly aligned within the code block
----

